//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "follows")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub follower_id: Uuid,
    pub following_id: Uuid,
    pub state: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::actors::Entity",
        from = "Column::FollowerId",
        to = "super::actors::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Follower,
    #[sea_orm(
        belongs_to = "super::actors::Entity",
        from = "Column::FollowingId",
        to = "super::actors::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Following,
}

impl Related<super::actors::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Follower.def()
    }
}
