//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub use super::activities::Entity as Activities;
pub use super::actors::Entity as Actors;
pub use super::follows::Entity as Follows;
pub use super::users::Entity as Users;
